### PR TITLE
GUI

### PR DESCRIPTION
**Pull request by Manny-op**
Basic GUI made and template to integrate with functions made.

### CODE REVIEW

**Review by winterfrost28 — COMMENTED** [review]
Let's put this gui in a class and call it in main.py.

**Review by winterfrost28 — CHANGES_REQUESTED** [review]
Place in a class, then call the GUI class in main.

**Comment by winterfrost28** [comment]
image
This is all I get when I run python3 gui.py, could you provide more info on how to run the program?

**Comment by Manny-op** [comment]
tkinter example

On both linux and windows the graphics appears like so. I am using python 3.10 however which may be an area of concern

to run the program i just used `python gui.py` but now managed to make it a class that is called in the main.py

**Pull request merged**
